apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-backend
  namespace: team-board
spec:
  replicas: 3
  selector:
    matchLabels:
      app: board-backend
  template:
    metadata:
      labels:
        app: board-backend
    spec:
      serviceAccountName: board-sa
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
