apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-board
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ysjysj1212/k8s-board-ops
    targetRevision: master
    path: charts/team-board
  destination:
    server: https://kubernetes.default.svc
    namespace: team-board
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
